### ISSUE TITLE
Add support for switching between Fahrenheit and Celsius

### ISSUE THREAD

**Issue by djcass44** [djcass44/chrome-nt-simplehome#2]
Methods:

1. Locale based

2. Toggle in extension settings (see #5 )

**Comment by PedAltuve** [comment]
I'd like to take a shot at this one

**Comment by PedAltuve** [comment]
Please check this [PR](https://github.com/djcass44/chrome-nt-simplehome/pull/11)

**Comment by djcass44** [comment]
Merged into canary in #11
